group:
  - resourceName: TestResource
    resourceUrl: /kapi/test
    timeOut: 3000
    routeList:
      - addres: http://127.0.0.1:8083
        weight: 1
      - addres: http://127.0.0.2:8084
        weight: 0
    interfaceDTOList:
      - resourceName: GetTokenInterface
        resourceUrl: /kapi/test/getToken
        handlerList:
          - TokenBaseComponent:20
        groupExtends: true